[connections.supabase]
SUPABASE_URL = "https://qheknfrepslenjavdpmi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoZWtuZnJlcHNsZW5qYXZkcG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzg5NTYsImV4cCI6MjA2MzgxNDk1Nn0.o2ztJjAfXpzmQSWCrjwFLP3B8cWONST2z2BVEcZHAOI"